// Generated by Haxe 4.1.5
package net.bulbyvr.example;

import haxe.root.*;

@SuppressWarnings(value={"rawtypes", "unchecked"})
public class ExampleMod extends haxe.lang.HxObject implements net.fabricmc.api.ModInitializer
{
	public ExampleMod(haxe.lang.EmptyObject empty)
	{
	}
	
	
	public ExampleMod()
	{
		//line 4 "C:\\Users\\benha\\Documents\\GitHub\\mc-haxe\\haxe-src\\net\\bulbyvr\\example\\ExampleMod.hx"
		net.bulbyvr.example.ExampleMod.__hx_ctor_net_bulbyvr_example_ExampleMod(this);
	}
	
	
	protected static void __hx_ctor_net_bulbyvr_example_ExampleMod(net.bulbyvr.example.ExampleMod __hx_this)
	{
	}
	
	
	public void onInitialize()
	{
		//line 6 "C:\\Users\\benha\\Documents\\GitHub\\mc-haxe\\haxe-src\\net\\bulbyvr\\example\\ExampleMod.hx"
		haxe.Log.trace.__hx_invoke2_o(0.0, "HELLO WORL", 0.0, new haxe.lang.DynamicObject(new java.lang.String[]{"className", "fileName", "methodName"}, new java.lang.Object[]{"net.bulbyvr.example.ExampleMod", "haxe-src/net/bulbyvr/example/ExampleMod.hx", "onInitialize"}, new java.lang.String[]{"lineNumber"}, new double[]{((double) (((double) (6) )) )}));
	}
	
	
	@Override public java.lang.Object __hx_getField(java.lang.String field, boolean throwErrors, boolean isCheck, boolean handleProperties)
	{
		//line 4 "C:\\Users\\benha\\Documents\\GitHub\\mc-haxe\\haxe-src\\net\\bulbyvr\\example\\ExampleMod.hx"
		{
			//line 4 "C:\\Users\\benha\\Documents\\GitHub\\mc-haxe\\haxe-src\\net\\bulbyvr\\example\\ExampleMod.hx"
			boolean __temp_executeDef1 = true;
			//line 4 "C:\\Users\\benha\\Documents\\GitHub\\mc-haxe\\haxe-src\\net\\bulbyvr\\example\\ExampleMod.hx"
			if (( field != null )) 
			{
				//line 4 "C:\\Users\\benha\\Documents\\GitHub\\mc-haxe\\haxe-src\\net\\bulbyvr\\example\\ExampleMod.hx"
				switch (field.hashCode())
				{
					case -83285297:
					{
						//line 4 "C:\\Users\\benha\\Documents\\GitHub\\mc-haxe\\haxe-src\\net\\bulbyvr\\example\\ExampleMod.hx"
						if (field.equals("onInitialize")) 
						{
							//line 4 "C:\\Users\\benha\\Documents\\GitHub\\mc-haxe\\haxe-src\\net\\bulbyvr\\example\\ExampleMod.hx"
							__temp_executeDef1 = false;
							//line 4 "C:\\Users\\benha\\Documents\\GitHub\\mc-haxe\\haxe-src\\net\\bulbyvr\\example\\ExampleMod.hx"
							return ((haxe.lang.Function) (new haxe.lang.Closure(this, "onInitialize")) );
						}
						
						//line 4 "C:\\Users\\benha\\Documents\\GitHub\\mc-haxe\\haxe-src\\net\\bulbyvr\\example\\ExampleMod.hx"
						break;
					}
					
					
				}
				
			}
			
			//line 4 "C:\\Users\\benha\\Documents\\GitHub\\mc-haxe\\haxe-src\\net\\bulbyvr\\example\\ExampleMod.hx"
			if (__temp_executeDef1) 
			{
				//line 4 "C:\\Users\\benha\\Documents\\GitHub\\mc-haxe\\haxe-src\\net\\bulbyvr\\example\\ExampleMod.hx"
				return super.__hx_getField(field, throwErrors, isCheck, handleProperties);
			}
			else
			{
				//line 4 "C:\\Users\\benha\\Documents\\GitHub\\mc-haxe\\haxe-src\\net\\bulbyvr\\example\\ExampleMod.hx"
				throw null;
			}
			
		}
		
	}
	
	
	@Override public java.lang.Object __hx_invokeField(java.lang.String field, java.lang.Object[] dynargs)
	{
		//line 4 "C:\\Users\\benha\\Documents\\GitHub\\mc-haxe\\haxe-src\\net\\bulbyvr\\example\\ExampleMod.hx"
		{
			//line 4 "C:\\Users\\benha\\Documents\\GitHub\\mc-haxe\\haxe-src\\net\\bulbyvr\\example\\ExampleMod.hx"
			boolean __temp_executeDef1 = true;
			//line 4 "C:\\Users\\benha\\Documents\\GitHub\\mc-haxe\\haxe-src\\net\\bulbyvr\\example\\ExampleMod.hx"
			if (( field != null )) 
			{
				//line 4 "C:\\Users\\benha\\Documents\\GitHub\\mc-haxe\\haxe-src\\net\\bulbyvr\\example\\ExampleMod.hx"
				switch (field.hashCode())
				{
					case -83285297:
					{
						//line 4 "C:\\Users\\benha\\Documents\\GitHub\\mc-haxe\\haxe-src\\net\\bulbyvr\\example\\ExampleMod.hx"
						if (field.equals("onInitialize")) 
						{
							//line 4 "C:\\Users\\benha\\Documents\\GitHub\\mc-haxe\\haxe-src\\net\\bulbyvr\\example\\ExampleMod.hx"
							__temp_executeDef1 = false;
							//line 4 "C:\\Users\\benha\\Documents\\GitHub\\mc-haxe\\haxe-src\\net\\bulbyvr\\example\\ExampleMod.hx"
							this.onInitialize();
						}
						
						//line 4 "C:\\Users\\benha\\Documents\\GitHub\\mc-haxe\\haxe-src\\net\\bulbyvr\\example\\ExampleMod.hx"
						break;
					}
					
					
				}
				
			}
			
			//line 4 "C:\\Users\\benha\\Documents\\GitHub\\mc-haxe\\haxe-src\\net\\bulbyvr\\example\\ExampleMod.hx"
			if (__temp_executeDef1) 
			{
				//line 4 "C:\\Users\\benha\\Documents\\GitHub\\mc-haxe\\haxe-src\\net\\bulbyvr\\example\\ExampleMod.hx"
				return super.__hx_invokeField(field, dynargs);
			}
			
		}
		
		//line 4 "C:\\Users\\benha\\Documents\\GitHub\\mc-haxe\\haxe-src\\net\\bulbyvr\\example\\ExampleMod.hx"
		return null;
	}
	
	
}


